name: 'PDF Optimizer'
description: 'Optimize PDFs with Ghostscript and verify integrity'
inputs:
  file-name:
    description: 'Name of the PDF file to optimize'
    required: true
  output-file:
    description: 'Output file path (if not specified, input file will be overwritten)'
    required: false
  quality-level:
    description: 'Quality level for optimization (screen, ebook, printer, prepress, default)'
    required: false
    default: 'prepress'
  test-string:
    description: 'Test string to verify CMap integrity'
    required: false
  convert-to-cmyk:
    description: 'Whether to convert to CMYK color space'
    required: false
    default: 'false'
outputs:
  page-count:
    description: 'Page count in the optimized PDF'
    value: ${{ steps.optimize.outputs.page-count }}
runs:
  using: 'composite'
  steps:
    - name: Optimize PDF
      id: optimize
      uses: docker://ghcr.io/qwrtln/pdf-optimizer:v1
      with:
        args: >
          --file-name "${{ inputs.file-name }}"
          --quality-level "${{ inputs.quality-level }}"
          --convert-to-cmyk "${{ inputs.convert-to-cmyk }}"
          --test-string "${{ inputs.test-string }}"
          --output-file "${{ inputs.output-file }}"
